---
- hosts: zookeepernodes
  vars:
    install_mode: "standalone"
  user: centos
  sudo: yes
  roles:
    # Java role from scratch
    - role: java
    # Zookeeper role from scratch
    # - role: zookeeper
