---
- hosts: all
  vars:
    install_mode: "standalone"
  user: centos
  sudo: yes
  roles:
    # Java role from scratch
    - role: java-jdk-install
    # Zookeeper role from scratch
    - role: zookeeper-install
