# Manual-ish task listing to get a specified Java version from the Oracle site.
# Currently using this as the main task for Java, will use Role version if this is insufficient.

  - name: Ensure wget is on the target machine
    yum:
      name: wget
      state: latest

  - name: Download Java
    command: "wget -q -O {{java_archive}} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_archive}}"

  # - name: Download Java w/ get_url
  #   get_url:
  #   url: {{download_url}}
  #   dest: /etc/foo.conf
  #   mode: 0440

  - name: Unpack archive
    command: "tar -zxf {{java_archive}} -C {{download_folder}} creates={{java_name}}"

  - name: Fix ownership
    file: state=directory path={{java_name}} owner=root group=root recurse=yes

  - name: Make Java available for system
    command: 'alternatives --install "/usr/bin/java" "java" "{{java_name}}/bin/java" 2000'

  - name: Clean up
    file: state=absent path={{java_archive}}
